FROM mcr.microsoft.com/devcontainers/base:bullseye
ARG FLUTTER_VERSION=3.19.6
ENV FLUTTER_HOME=/opt/flutter
ENV PATH=${FLUTTER_HOME}/bin:${PATH}

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    git curl unzip wget xz-utils zip libglu1-mesa openjdk-17-jdk \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p ${FLUTTER_HOME} && \
    cd /opt && \
    wget -q "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz" && \
    tar xf "flutter_linux_${FLUTTER_VERSION}-stable.tar.xz" && \
    rm "flutter_linux_${FLUTTER_VERSION}-stable.tar.xz" && \
    chown -R vscode:vscode ${FLUTTER_HOME}

USER vscode
RUN flutter precache && \
    yes | flutter doctor --android-licenses
WORKDIR /workspaces/MaxDiagnostic
CMD [ "sleep", "infinity" ]